from enum import StrEnum


class UserRole(StrEnum):
    CUSTOMER = "CUSTOMER"
    PROVIDER = "PROVIDER"
    ADMIN = "ADMIN"


class VerificationStatus(StrEnum):
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    DISABLED = "DISABLED"


class AvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"


class BookingStatus(StrEnum):
    REQUESTED = "REQUESTED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED_BY_CUSTOMER = "CANCELLED_BY_CUSTOMER"
    CANCELLED_BY_PROVIDER = "CANCELLED_BY_PROVIDER"
    CANCELLED_BY_ADMIN = "CANCELLED_BY_ADMIN"


class PaymentMode(StrEnum):
    CASH_ON_SERVICE = "CASH_ON_SERVICE"
    ONLINE = "ONLINE"


class PaymentStatus(StrEnum):
    NOT_APPLICABLE_YET = "NOT_APPLICABLE_YET"
    CASH_PENDING = "CASH_PENDING"
    PAID_CASH = "PAID_CASH"
    DISPUTED = "DISPUTED"


class ReviewStatus(StrEnum):
    VISIBLE = "VISIBLE"
    HIDDEN_BY_ADMIN = "HIDDEN_BY_ADMIN"
